### ISSUE TITLE
Can you release on bower as well?

### ISSUE THREAD

**Issue by randing89** [blakeembrey/camel-case#6]
Thanks

**Comment by blakeembrey** [comment]
@randing89 Maybe. Do you know how to handle dependencies properly on Bower (with CommonJS)? I've always had a hard time using it because it forces you to use non-modular systems.

**Comment by randing89** [comment]
Thanks. I use webpack. It reads bower.json and resolve dependencies according to the “main” property, pretty much like NPM. A bower package with commonjs makes no difference to a NPM package actually. It just if I’m using it in front-end I'd like to keep it in bower's folder to make it more clear.

**Comment by blakeembrey** [comment]
@randing89 Sorry for the delay, just getting around to fixing it all up. It looks like `upper-case` is already a component, so maybe I'll go with a different naming scheme with `bower`? What do you think of `case-{type}` like `case-camel`?

**Comment by randing89** [comment]
That will do. Thanks!


Regards,
Ran Ding

**Comment by blakeembrey** [comment]
Sorry, I just realised why I hate Bower again. I can't just do this because all the requires will be different. :sob: Any thoughts? I might have to ask for the `upper-case` library or you could log an issue there.

**Comment by randing89** [comment]
Hi

What you can do is use a packing tool like Browserify or Webpack to pack all the NPM dependencies and your source files to a single release file then pointing the bower.json to that file. In this case you will not having any dependency in bower since everything is in that big packed file. I suggest you to have a look at this repo https://github.com/bendrucker/creditcards <https://github.com/bendrucker/creditcards>. It is similar to your case as it is a NPM package as well as a bower package.

Cheers

**Comment by blakeembrey** [comment]
I do that in other repos, but it's too much dependency duplication and inflexible. It'd be nice to not require it. By the way, do you know how he's doing the releases folder? Doesn't it need to be checked in with git for bower? You can always just do an install from github. Actually, that's what I'll do - dependencies can be git links for bower.

**Comment by randing89** [comment]
Yeah. Probably easier to just use github url. I will go with that.
Thanks.
