### ISSUE TITLE
Make numbergrouping optional

### ISSUE THREAD

**Issue by Richard-Meijer** [blakeembrey/camel-case#7]
I expected 'key_1_1' to result in 'key11'. Is it possible to make the explicit number group splitting optional?

**Comment by blakeembrey** [comment]
@Richard-Meijer Yes, I think that makes sense. I'll add an option for you tonight. Just be aware that the result will not be reversible.

**Comment by blakeembrey** [comment]
Published with `v1.2.0`.

**Comment by Richard-Meijer** [comment]
Thanks for the quick response! Works perfectly.
